spring:
  application:
    name: pedidos
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
rabbitmq:
  #QUEUE
  queue:
    pedidos: pedidos.entrada.clayton
  host: localhost
  port: 5672
  username: guest
  password: guest